package update

import (
	"crypto/ed25519"
	_ "embed"
	"encoding/base64"
	"encoding/json"
	"fmt"

	"cnb.cool/shichao402/relkit/sdk"
)

//go:generate go run generate_relkit.go

// Embedded copy of repo-root relkit.json (SSOT for signing.publicKeys).
// Do not edit this file by hand — change ../../relkit.json then run:
//
//	go generate ./internal/update
//
//go:embed embed/relkit.json
var embeddedRelkitJSON []byte

type relkitPublicKey struct {
	KeyID           string `json:"keyId"`
	PublicKeyBase64 string `json:"publicKeyBase64"`
}

type relkitFile struct {
	Signing struct {
		KeyID      string           `json:"keyId"`
		PublicKeys []relkitPublicKey `json:"publicKeys"`
	} `json:"signing"`
}

func trustedKeys() (sdk.TrustedKeys, error) {
	var cfg relkitFile
	if err := json.Unmarshal(embeddedRelkitJSON, &cfg); err != nil {
		return nil, fmt.Errorf("parse embedded relkit.json: %w", err)
	}
	if len(cfg.Signing.PublicKeys) == 0 {
		return nil, fmt.Errorf("embedded relkit.json has no signing.publicKeys")
	}
	keys := make(sdk.TrustedKeys, len(cfg.Signing.PublicKeys))
	for _, pk := range cfg.Signing.PublicKeys {
		if pk.KeyID == "" {
			return nil, fmt.Errorf("embedded public key missing keyId")
		}
		raw, err := base64.StdEncoding.DecodeString(pk.PublicKeyBase64)
		if err != nil {
			return nil, fmt.Errorf("decode public key %q: %w", pk.KeyID, err)
		}
		if len(raw) != ed25519.PublicKeySize {
			return nil, fmt.Errorf("public key %q: invalid length %d", pk.KeyID, len(raw))
		}
		keys[pk.KeyID] = ed25519.PublicKey(raw)
	}
	if _, ok := keys[keyID]; !ok {
		return nil, fmt.Errorf("embedded relkit.json missing required keyId %q", keyID)
	}
	return keys, nil
}
